from enum import Enum

class MessageType(Enum):
	UNDEFINED = 0,
	SHOW_MAP = 1,
	SHOW_PROFILE = 2,
	SHOW_FAVOURITE = 3,
	SHOW_ADD_NEW = 4,
	SHOW_SIGN_UP_SIGN_IN = 5,
	SHOW_SIGN_UP = 6,
	SHOW_SIGN_IN = 7,
	SHOW_COMMENTS = 8,

	SIGN_IN = 9,
	SIGN_UP = 10,
	LOGOUT = 11,

	ADD_NEW_SHAWA = 12,
	SEARCH = 13,
	MORE = 14,
	FAVOURITE_ADD = 15,
	FAVOURITE_REMOVE = 16,
	COMMENT_ADD = 17
	

class UserType(Enum):
	UNREGISTERED = 0,
	USER = 1,
	ADMIN = 2